### ISSUE TITLE
Hi im reporting a bug dedicated for Amethyst Shield. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [Artistry-mods/sculklatch#1]
The bug in Amethyst Shield is that it is not rendering the item but the 3d is rendered.
![Screenshot 2024-07-12 145903](https://github.com/user-attachments/assets/ba81502c-7be4-4747-a232-6cf3ca0e6818)

**Comment by HerrChaos** [comment]
hello, thanks for your report but I can not reproduce this issue. since for me it looks just like this.
![image](https://github.com/user-attachments/assets/a6cef5a0-a17d-4df6-a7e7-972db7c80586)
can you tell me what mods you are using. Maybe one of them breaks compatibility.

**Comment by makumaku1974** [comment]
tbh i dont really know what it was causing but i could send a log file. And I have about 571 mods right now.

**Comment by makumaku1974** [comment]
I will close this issue because it is fixed.

**Comment by makumaku1974** [comment]
![Screenshot 2024-07-12 205129](https://github.com/user-attachments/assets/b9a54b09-ec7c-47d8-92ae-e49b0b48e707)
